name: APP CI/CD

on:
  push:
    paths:
      - '*'
    branches:
      - main

  pull_request:
    paths:
      - '*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build the APP
        run: npm run build

      - name: Run tests
        run: npm run test
